###
get http://localhost:4040/api/user

###
post http://localhost:4040/api/user
Content-Type: application/json

{
  "username":"muhammedss",
  "password":"iluminate"  
}

###
post http://localhost:4040/api/login
Content-Type: application/json

{
    "username":"Abdulmujib",
    "password":"idapamide"
}
###
get http://localhost:4040/api/messages
###
post http://localhost:4040/api/messages/Abdulmuj
Content-Type: application/json

{
  "message":"you are a very stupid person"  
}