###
get http://localhost:4040/api/user

###
post http://localhost:4040/api/user
Content-Type: application/json

{
  "username":"muhammed",
  "password":"iluminate"  
}

###
post http://localhost:4040/api/login
Content-Type: application/json

{
    "username":"Abdulmujib",
    "password":"idapamide"
}